# Generated by Django 6.1.1 on 2026-09-08 15:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "policy_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "provider_policy_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("destination_name", models.CharField(max_length=200)),
                ("plan_name", models.CharField(max_length=100)),
                ("medical_limit", models.CharField(default="€30,000", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_ISSUANCE", "Pending Issuance"),
                            ("ISSUED", "Issued"),
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="ISSUED",
                        max_length=25,
                    ),
                ),
                (
                    "certificate_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Complete electronic certificate and terms payload",
                    ),
                ),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Policies",
                "ordering": ["-issued_at"],
            },
        ),
    ]
