# Generated by Django 6.1.1 on 2026-09-08 15:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coverage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MEDICAL", "Medical & Health"),
                            ("BAGGAGE", "Baggage & Belongings"),
                            ("FLIGHT", "Flight & Trip Delay"),
                            ("COVID", "COVID-19 Protection"),
                            ("SPORTS", "Sports & Activities"),
                            ("LEGAL", "Legal & Liability"),
                            ("ASSISTANCE", "Emergency Assistance"),
                        ],
                        default="MEDICAL",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="UI icon identifier",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("TRAVEL", "Travel Insurance"),
                            ("VISA", "Visa & Schengen Insurance"),
                            ("SPORTS", "Sports & Extreme Activities"),
                            ("ANNUAL", "Multi-Trip Annual Insurance"),
                            ("FAMILY", "Family Travel Insurance"),
                        ],
                        default="TRAVEL",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TravelType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "risk_multiplier",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["risk_multiplier"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "base_price_per_day",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=10),
                ),
                ("currency", models.CharField(default="EUR", max_length=10)),
                (
                    "medical_limit_display",
                    models.CharField(default="€30,000", max_length=50),
                ),
                ("is_popular", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "base_price_per_day"],
            },
        ),
        migrations.CreateModel(
            name="PlanCoverage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "limit_display",
                    models.CharField(
                        help_text="e.g. €30,000 or Included", max_length=100
                    ),
                ),
                (
                    "limit_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "deductible_display",
                    models.CharField(
                        default="€0", help_text="e.g. €0 or €50", max_length=50
                    ),
                ),
                ("is_included", models.BooleanField(default=True)),
                ("is_optional_addon", models.BooleanField(default=False)),
                (
                    "addon_price_per_day",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "coverage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_coverages",
                        to="products.coverage",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverages",
                        to="products.plan",
                    ),
                ),
            ],
            options={
                "ordering": ["plan", "coverage__category", "coverage__name"],
                "unique_together": {("plan", "coverage")},
            },
        ),
        migrations.CreateModel(
            name="PlanTravelType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "surcharge_per_day",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_types",
                        to="products.plan",
                    ),
                ),
                (
                    "travel_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_travel_types",
                        to="products.traveltype",
                    ),
                ),
            ],
            options={
                "unique_together": {("plan", "travel_type")},
            },
        ),
    ]
